- name: Enable Syncthing GUI
  community.general.xml:
    path: "~/.local/state/syncthing/config.xml"
    xpath: /configuration/gui
    attribute: enabled    
    #value: 'false'
    value: 'true' # Can't disable because CLI uses it

- name: Set VPS Network and Discovery Options
  community.general.xml:
    path: "~/.local/state/syncthing/config.xml"
    xpath: "/configuration/options/{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: 'relaysEnabled', value: 'false' }
    - { key: 'globalAnnounceEnabled', value: 'false' }
    - { key: 'localAnnounceEnabled', value: 'true' }
    - { key: 'natEnabled', value: 'true' }