- debug:
    msg: "Setting up Syncthing for trusted device"

- name: Collect all blackbox device IDs into an array
  set_fact:
    blackbox_ids: "{{ groups['syncthing_blackboxes'] 
      | map('extract', hostvars) 
      | selectattr('syncthing_device_id', 'defined') 
      | map(attribute='syncthing_device_id') 
      | list }}"


- name: Add Blackboxes to Local Machine
  ansible.builtin.command:
    cmd: >
      syncthing cli config devices add 
      --device-id {{ item }} 
      --name {{ hostvars[target_host]['ansible_hostname'] | default(target_host) }}
      --untrusted       
  loop: "{{ blackbox_ids }}"
  loop_control:
    extended: true
  vars:
    target_host: "{{ groups['syncthing_blackboxes'][ansible_loop.index0] }}"

# Remove ALL existing addresses for each device
- name: XML | Remove all device addresses
  community.general.xml:
    path: "~/.local/state/syncthing/config.xml"
    xpath: "/configuration/device[@id='{{ item }}']/address"
    state: absent
  loop: "{{ blackbox_ids }}"
  notify: Restart Syncthing

# Re-add correct TCP + QUIC addresses
- name: XML | Add TCP + QUIC addresses
  community.general.xml:
    path: "~/.local/state/syncthing/config.xml"
    xpath: "/configuration/device[@id='{{ item.0 }}']"
    add_children:
      - address: "tcp://{{ item.1 }}:22000"
      - address: "quic://{{ item.1 }}:22000"
  loop: "{{ blackbox_ids | zip(groups['syncthing_blackboxes'] | map('extract', hostvars, 'blackbox_ip')) | list }}"
  notify: Restart Syncthing