- name: Create separate user for Syncthing on blackboxes
  become: yes
  hosts: syncthing_blackboxes
  tasks:
    - name: Load Syncthing role defaults
      include_vars:
        file: roles/syncthing/defaults/main.yml

    - name: Ensure Syncthing user exists and capture their info
      user:
        name: "{{ syncthing_user }}"
        shell: /bin/bash
        state: present     

    - name: Enable lingering for the Syncthing user
      become: yes
      command: "loginctl enable-linger {{ syncthing_user }}"
      args:
        creates: "/var/lib/systemd/linger/{{ syncthing_user }}"

- name: Syncthing Blackboxes initial setup
  hosts: syncthing_blackboxes  
  become: yes
  become_user: "{{ syncthing_user }}"
  gather_facts: yes
  roles:
    - role: debian
      become_user: root
    - role: syncthing
  tasks:
    - name: Set up Syncthing service for a blackbox machine
      include_role:
        name: syncthing
        tasks_from: init_blackbox.yml    

- name: Syncthing local initial setup
  hosts: localhost
  connection: local
  become: no
  vars:
    syncthing_user: "{{ ansible_user_id }}"
    is_blackbox: no
  roles:
    - role: debian
      become: yes
    - role: syncthing      
  tasks:
    - name: Set up local machine as a trusted device
      include_role:
        name: syncthing
        tasks_from: init_trusted_device.yml  

- name: Add local machine as trusted device to blackbox
  hosts: syncthing_blackboxes
  vars_files:
    - roles/syncthing/defaults/main.yml
  become: yes
  become_user: "{{ syncthing_user }}"
  tasks:
    - name: Add Local Device to Blackbox
      command:
        cmd: >
          syncthing cli config devices add 
          --device-id {{ hostvars['localhost']['syncthing_device_id'] }} 
          --name {{ hostvars['localhost']['ansible_hostname'] }}
          --auto-accept-folders

    - name: CLI | Get list of all Folder IDs
      ansible.builtin.command: "syncthing cli config folders list"
      register: folder_list
      changed_when: false

    - name: CLI | Add Localhost to every folder
      ansible.builtin.command:
        cmd: "syncthing cli config folders {{ item }} devices add --device-id {{ hostvars['localhost']['syncthing_device_id'] }}"
      loop: "{{ folder_list.stdout_lines }}"
      register: share_result
      # Ignore if the device is already attached to the folder
      failed_when: 
        - share_result.rc != 0 
        - "'already exists' not in share_result.stderr"
      changed_when: share_result.rc == 0